version: "3.8"

services:
  myipservice:
    build:
      context: .  # Path to your project directory
      dockerfile: Dockerfile  # Name of the Dockerfile (if it's named something else, specify here)
    ports:
      - "100:8080"   # Maps host port 100 to container port 8080
      - "101:443"    # Maps host port 101 to container port 443
    environment:
      AzureDns__SubscriptionId: "0574a3b5-5e81-4710-94ee-80824c764a71"
      AzureDns__ResourceGroupName: "home"
      AzureDns__DnsZoneName: "kersenveld.nl"
      AzureDns__RecordSetName: "home"
      Ipify__QueryUri: "https://api.ipify.org/"
      Sync__DoSync: "false"
      Sync__Timeout: "00:01:00"
    restart: always  # Keeps the container running until manually stopped
